### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by reginfo** [EXreaction/phpbb-tracker#2]
Hi!
Today try to install this mod and I have problems with it!
May be you can help me!

We using Wordpress with phpBB3 integration thru wp-united mod.
When I try to install your mod thru automod all go ok until the message when I need to open mypage/phpbb3/install/index.php.
If I open my home page (WP) I see phpbb3 page but it looks horrible (attachment 1).
![1](https://f.cloud.github.com/assets/4628571/616893/577f97d0-ce81-11e2-966b-dba4c3b77421.jpg)
But if I open install.index.php page i see this screen (attachment 2)
![2](https://f.cloud.github.com/assets/4628571/616903/91cb46a0-ce81-11e2-9d5e-c10c8660772f.jpg)
Where I can`t choose anything.

It is demo site, because I don`t want to destroy working ONE, but I really want to install it on working one.

Can you help me?

Best Regards, 
Deniss

**Comment by EXreaction** [comment]
It seems like this is some sort of issue with WP-United, I would contact them to figure out what is going on.
